#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_gitlab_branch_regex="^(hotfix|fix|enhance|feature)-#[0-9]+-[a-z0-9-]+$"
test_branch_regex="^test(-[a-z]+)+$"

test_branch_regex="^($test_branch_regex)$"
valid_gitlab_branch_regex="^($valid_gitlab_branch_regex)$"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract:\n $valid_gitlab_branch_regex \n $test_branch_regex  \n examples: \n"
message+="\033[32m-fix-#3-update-login-screen-ui\033[0m \n\033[32m-test-calendar-widget-time-tracking\033[0m \n"
message+="\033[31mYour commit will be rejected. You should rename your branch to a valid name and try again.\033[0m"

if ! [[ $local_branch =~ $test_branch_regex ]] && ! [[ $local_branch =~ $valid_gitlab_branch_regex ]]
then
    echo -e "$message"
    exit 1
fi

exit 0
